name: Deploy Darwin Platform

on:
  push:
    branches: [ main ]
    paths:
      - 'bypass-git-deploy.html'
      - '.github/workflows/deploy.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Create dist folder
      run: |
        mkdir -p dist
        
    - name: Copy platform file
      run: |
        cp bypass-git-deploy.html dist/index.html
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        force_orphan: true 